steps:
  build:
    when:
      event: push
    image: node
    environment:
      TOKEN:
        from_secret: TOKEN
      EMAIL:
        from_secret: EMAIL
      USER:
        from_secret: USER
      REPO:
        from_secret: REPO
      BASE_HREF:
        from_secret: BASE_HREF
    commands:
      # Avoid permission denied errors
      - chmod -R a+w .
      # Set up git in a working way
      - git config --global --add safe.directory /woodpecker/src/codeberg.org/$USER/$REPO/_site
      - git config --global user.email "$EMAIL"
      - git config --global user.name "CI Builder"
      # clone and move the target repo
      - git clone -b pages https://codeberg.org/$USER/$REPO.git _site
      - chmod -R a+w _site
      - cd _site
      # Prepare for push
      - git remote set-url origin https://$TOKEN@codeberg.org/$USER/$REPO.git
      - cd ..
      # Run 11ty build stage
      - npm install
      - BASE_HREF="$BASE_HREF" npm run build
      # Set up custom custom domains
      # - cp .domains _site/
      # Push to target
      - cd _site
      - git add -A
      - git commit -m "Woodpecker CI 11ty Build at $( env TZ=Europe/Prague date +"%Y-%m-%d %X %Z" )"
      - git push -u origin pages

