name: '♿ Pa11y'
on: pull_request

jobs:
  pa11y:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@latest
      # - uses: Hesedi3l/pa11y-actions@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:8080
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:8080 --exit
